# Generated by Django 2.2.10 on 2021-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
