# Generated by Django 2.2.10 on 2021-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210505_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='startDate',
            field=models.DateField(),
        ),
    ]
