# Generated by Django 2.2.10 on 2021-05-05 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210505_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='option',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='option',
            field=models.ManyToManyField(blank=True, to='backend.Option'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='submitTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 17, 12, 7, 286085), editable=False),
        ),
    ]
